name: Create Tag and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly grant permission to push tags and create releases
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from file
        id: get_version
        run: |
          VERSION=$(cat nexaHealthVersion | tr -d '\n')
          if [ -z "$VERSION" ]; then
            echo "Error: Version from file is empty" >&2
            exit 1
          fi
          echo "TAG_NAME=$VERSION"
          echo "TAG_NAME=$VERSION" >> $GITHUB_ENV

      - name: Get previous tag
        id: get_prev_tag
        run: |
          PREV_TAG=$(git tag --sort=-v:refname | head -n 1 2>/dev/null)
          echo "PREV_TAG=$PREV_TAG"
          echo "PREV_TAG=$PREV_TAG" >> $GITHUB_ENV

      - name: Generate release notes
        id: generate_notes
        run: |
          if [ -n "$PREV_TAG" ]; then
            NOTES=$(git log --oneline $PREV_TAG..HEAD)
          else
            NOTES=$(git log --oneline)
          fi
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Git Tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        run: |
          gh release create "$TAG_NAME" --title "Release $TAG_NAME" --notes "$RELEASE_NOTES"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
